apiVersion: apps/v1
kind: Deployment
metadata:
   name: editapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: editapi
  template:
    metadata:
      labels:
        app: editapi
    spec:
      containers:
      - name: editapi
        image: shehan97105/editservice:latest
        ports:
        - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: editapi
  labels:
    app: editapi
spec:
  selector:
    type: NodePort
    app: editapi
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003