apiVersion: apps/v1
kind: Deployment
metadata:
   name: editapi-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: editapi-prod
  strategry:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: editapi-prod
    spec:
      containers:
      - name: editapi-prod
        image: shehan97105/editservice:latest
        ports:
        - containerPort: 5003

